// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TEAyudo_JT;

#nullable disable

namespace TEAyudo_JT.Migrations
{
    [DbContext(typeof(TEAyudoContext))]
    [Migration("20230904021639_CreateDB_diseno2")]
    partial class CreateDB_diseno2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AcompananteObraSocial", b =>
                {
                    b.Property<int>("AcompanantesAcompananteId")
                        .HasColumnType("int");

                    b.Property<int>("ObrasSocialesObraSocialId")
                        .HasColumnType("int");

                    b.HasKey("AcompanantesAcompananteId", "ObrasSocialesObraSocialId");

                    b.HasIndex("ObrasSocialesObraSocialId");

                    b.ToTable("AcompananteObraSocial");
                });

            modelBuilder.Entity("TEAyudo_JT.Acompanante", b =>
                {
                    b.Property<int>("AcompananteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AcompananteId"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contacto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Documentacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Domicilio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<int>("Especialidad")
                        .HasColumnType("int");

                    b.Property<int>("EstadoUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Experiencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotoPerfil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ObraSocialId")
                        .HasColumnType("int");

                    b.Property<int>("PostulacionId")
                        .HasColumnType("int");

                    b.Property<int>("TipoUsuarioId")
                        .HasColumnType("int");

                    b.HasKey("AcompananteId");

                    b.ToTable("Acompanantes");
                });

            modelBuilder.Entity("TEAyudo_JT.DisponibilidadHoraria", b =>
                {
                    b.Property<int>("DisponibilidadHorariaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DisponibilidadHorariaId"));

                    b.Property<DateTime>("HorarioFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HorarioInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostulacionId")
                        .HasColumnType("int");

                    b.HasKey("DisponibilidadHorariaId");

                    b.HasIndex("PostulacionId");

                    b.ToTable("DisponibilidadHorarias");
                });

            modelBuilder.Entity("TEAyudo_JT.Especialidad", b =>
                {
                    b.Property<int>("EspecialidadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EspecialidadId"));

                    b.Property<int?>("AcompananteId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EspecialidadId");

                    b.HasIndex("AcompananteId");

                    b.ToTable("Especialidades");
                });

            modelBuilder.Entity("TEAyudo_JT.EstadoPostulacion", b =>
                {
                    b.Property<int>("EstadoPostulacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadoPostulacionId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PostulacionId")
                        .HasColumnType("int");

                    b.HasKey("EstadoPostulacionId");

                    b.HasIndex("PostulacionId");

                    b.ToTable("EstadoPostulaciones");
                });

            modelBuilder.Entity("TEAyudo_JT.EstadoUsuario", b =>
                {
                    b.Property<int>("EstadoUsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadoUsuarioId"));

                    b.Property<int?>("AcompananteId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TutorId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("EstadoUsuarioId");

                    b.HasIndex("AcompananteId");

                    b.HasIndex("TutorId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("EstadoUsuario");
                });

            modelBuilder.Entity("TEAyudo_JT.ObraSocial", b =>
                {
                    b.Property<int>("ObraSocialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ObraSocialId"));

                    b.Property<int>("AcompananteId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ObraSocialId");

                    b.ToTable("ObrasSociales");
                });

            modelBuilder.Entity("TEAyudo_JT.Paciente", b =>
                {
                    b.Property<int>("PacienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PacienteId"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiagnosticoTEA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TutorId")
                        .HasColumnType("int");

                    b.HasKey("PacienteId");

                    b.HasIndex("TutorId");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("TEAyudo_JT.Postulacion", b =>
                {
                    b.Property<int>("PostulacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostulacionId"));

                    b.Property<int>("AcompananteId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisponibilidadHorariaId")
                        .HasColumnType("int");

                    b.Property<int>("EspecliadadId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoPostulacionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("ObraSocialId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PostulacionId");

                    b.HasIndex("AcompananteId");

                    b.ToTable("Postulaciones");
                });

            modelBuilder.Entity("TEAyudo_JT.TipoUsuario", b =>
                {
                    b.Property<int>("TipoUsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoUsuarioId"));

                    b.Property<int?>("AcompananteId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TutorId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("TipoUsuarioId");

                    b.HasIndex("AcompananteId");

                    b.HasIndex("TutorId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TiposDeUsuario");
                });

            modelBuilder.Entity("TEAyudo_JT.Tutor", b =>
                {
                    b.Property<int>("TutorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TutorId"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CertUniDisc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Domicilio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<int>("EstadoUsuario")
                        .HasColumnType("int");

                    b.Property<string>("FotoPerfil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.Property<int>("TipoUsuarioId")
                        .HasColumnType("int");

                    b.HasKey("TutorId");

                    b.ToTable("Tutores");
                });

            modelBuilder.Entity("TEAyudo_JT.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Domicilio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<int>("EstadoUsuario")
                        .HasColumnType("int");

                    b.Property<string>("FotoPerfil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoUsuarioId")
                        .HasColumnType("int");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("AcompananteObraSocial", b =>
                {
                    b.HasOne("TEAyudo_JT.Acompanante", null)
                        .WithMany()
                        .HasForeignKey("AcompanantesAcompananteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TEAyudo_JT.ObraSocial", null)
                        .WithMany()
                        .HasForeignKey("ObrasSocialesObraSocialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TEAyudo_JT.DisponibilidadHoraria", b =>
                {
                    b.HasOne("TEAyudo_JT.Postulacion", null)
                        .WithMany("DisponibilidadesHoraria")
                        .HasForeignKey("PostulacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TEAyudo_JT.Especialidad", b =>
                {
                    b.HasOne("TEAyudo_JT.Acompanante", null)
                        .WithMany("Especialidades")
                        .HasForeignKey("AcompananteId");
                });

            modelBuilder.Entity("TEAyudo_JT.EstadoPostulacion", b =>
                {
                    b.HasOne("TEAyudo_JT.Postulacion", null)
                        .WithMany("EstadosDePostulacion")
                        .HasForeignKey("PostulacionId");
                });

            modelBuilder.Entity("TEAyudo_JT.EstadoUsuario", b =>
                {
                    b.HasOne("TEAyudo_JT.Acompanante", null)
                        .WithMany("EstadosDeUsuario")
                        .HasForeignKey("AcompananteId");

                    b.HasOne("TEAyudo_JT.Tutor", null)
                        .WithMany("EstadosDeUsuario")
                        .HasForeignKey("TutorId");

                    b.HasOne("TEAyudo_JT.Usuario", null)
                        .WithMany("EstadosDeUsuario")
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("TEAyudo_JT.Paciente", b =>
                {
                    b.HasOne("TEAyudo_JT.Tutor", null)
                        .WithMany("Pacientes")
                        .HasForeignKey("TutorId");
                });

            modelBuilder.Entity("TEAyudo_JT.Postulacion", b =>
                {
                    b.HasOne("TEAyudo_JT.Acompanante", null)
                        .WithMany("Postulaciones")
                        .HasForeignKey("AcompananteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TEAyudo_JT.TipoUsuario", b =>
                {
                    b.HasOne("TEAyudo_JT.Acompanante", null)
                        .WithMany("TiposDeUsuario")
                        .HasForeignKey("AcompananteId");

                    b.HasOne("TEAyudo_JT.Tutor", null)
                        .WithMany("TiposDeUsuario")
                        .HasForeignKey("TutorId");

                    b.HasOne("TEAyudo_JT.Usuario", null)
                        .WithMany("TiposDeUsuario")
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("TEAyudo_JT.Acompanante", b =>
                {
                    b.Navigation("Especialidades");

                    b.Navigation("EstadosDeUsuario");

                    b.Navigation("Postulaciones");

                    b.Navigation("TiposDeUsuario");
                });

            modelBuilder.Entity("TEAyudo_JT.Postulacion", b =>
                {
                    b.Navigation("DisponibilidadesHoraria");

                    b.Navigation("EstadosDePostulacion");
                });

            modelBuilder.Entity("TEAyudo_JT.Tutor", b =>
                {
                    b.Navigation("EstadosDeUsuario");

                    b.Navigation("Pacientes");

                    b.Navigation("TiposDeUsuario");
                });

            modelBuilder.Entity("TEAyudo_JT.Usuario", b =>
                {
                    b.Navigation("EstadosDeUsuario");

                    b.Navigation("TiposDeUsuario");
                });
#pragma warning restore 612, 618
        }
    }
}
