// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TEAyudo_JT;

#nullable disable

namespace TEAyudo_JT.Migrations
{
    [DbContext(typeof(TEAyudoContext))]
    partial class TEAyudoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AcompananteObraSocial", b =>
                {
                    b.Property<int>("AcompanantesAcompananteId")
                        .HasColumnType("int");

                    b.Property<int>("ObrasSocialesObraSocialId")
                        .HasColumnType("int");

                    b.HasKey("AcompanantesAcompananteId", "ObrasSocialesObraSocialId");

                    b.HasIndex("ObrasSocialesObraSocialId");

                    b.ToTable("AcompananteObraSocial");
                });

            modelBuilder.Entity("ChatConversacion", b =>
                {
                    b.Property<int>("ChatConversacionId")
                        .HasColumnType("int");

                    b.Property<int>("AcompananteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.HasKey("ChatConversacionId");

                    b.ToTable("ChatConversaciones");
                });

            modelBuilder.Entity("EstadoPostulacionPostulacion", b =>
                {
                    b.Property<int>("EstadosDePostulacionEstadoPostulacionId")
                        .HasColumnType("int");

                    b.Property<int>("PostulacionesPostulacionId")
                        .HasColumnType("int");

                    b.HasKey("EstadosDePostulacionEstadoPostulacionId", "PostulacionesPostulacionId");

                    b.HasIndex("PostulacionesPostulacionId");

                    b.ToTable("EstadoPostulacionPostulacion");
                });

            modelBuilder.Entity("TEAyudo_JT.Acompanante", b =>
                {
                    b.Property<int>("AcompananteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AcompananteId"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ChatConversacionId")
                        .HasColumnType("int");

                    b.Property<string>("Contacto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Documentacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Domicilio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<int>("Especialidad")
                        .HasColumnType("int");

                    b.Property<int>("EstadoUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Experiencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotoPerfil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ObraSocialId")
                        .HasColumnType("int");

                    b.Property<int>("PostulacionId")
                        .HasColumnType("int");

                    b.Property<int>("TipoUsuarioId")
                        .HasColumnType("int");

                    b.HasKey("AcompananteId");

                    b.HasIndex("ChatConversacionId");

                    b.ToTable("Acompanantes");
                });

            modelBuilder.Entity("TEAyudo_JT.ChatMensaje", b =>
                {
                    b.Property<int>("ChatMensajeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChatMensajeId"));

                    b.Property<int>("ChatConversacionId")
                        .HasColumnType("int");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.Property<int>("RemitenteId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("ChatMensajeId");

                    b.HasIndex("ChatConversacionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ChatMensaje");
                });

            modelBuilder.Entity("TEAyudo_JT.DisponibilidadHoraria", b =>
                {
                    b.Property<int>("DisponibilidadHorariaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DisponibilidadHorariaId"));

                    b.Property<DateTime>("HorarioFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HorarioInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostulacionId")
                        .HasColumnType("int");

                    b.HasKey("DisponibilidadHorariaId");

                    b.HasIndex("PostulacionId");

                    b.ToTable("DisponibilidadHorarias");
                });

            modelBuilder.Entity("TEAyudo_JT.Especialidad", b =>
                {
                    b.Property<int>("EspecialidadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EspecialidadId"));

                    b.Property<int?>("AcompananteId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EspecialidadId");

                    b.HasIndex("AcompananteId");

                    b.ToTable("Especialidades");
                });

            modelBuilder.Entity("TEAyudo_JT.EstadoPostulacion", b =>
                {
                    b.Property<int>("EstadoPostulacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadoPostulacionId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EstadoPostulacionId");

                    b.ToTable("EstadoPostulaciones");
                });

            modelBuilder.Entity("TEAyudo_JT.EstadoUsuario", b =>
                {
                    b.Property<int>("EstadoUsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadoUsuarioId"));

                    b.Property<int?>("AcompananteId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("EstadoUsuarioId");

                    b.HasIndex("AcompananteId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("EstadoUsuario");
                });

            modelBuilder.Entity("TEAyudo_JT.ObraSocial", b =>
                {
                    b.Property<int>("ObraSocialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ObraSocialId"));

                    b.Property<int>("AcompananteId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ObraSocialId");

                    b.ToTable("ObrasSociales");
                });

            modelBuilder.Entity("TEAyudo_JT.Paciente", b =>
                {
                    b.Property<int>("PacienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PacienteId"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiagnosticoTEA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TutorUsuarioId")
                        .HasColumnType("int");

                    b.HasKey("PacienteId");

                    b.HasIndex("TutorUsuarioId");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("TEAyudo_JT.Postulacion", b =>
                {
                    b.Property<int>("PostulacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostulacionId"));

                    b.Property<int>("AcompananteId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisponibilidadHorariaId")
                        .HasColumnType("int");

                    b.Property<int>("EspecliadadId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoPostulacionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("ObraSocialId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PostulacionId");

                    b.HasIndex("AcompananteId");

                    b.ToTable("Postulaciones");
                });

            modelBuilder.Entity("TEAyudo_JT.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Domicilio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<int>("EstadoUsuario")
                        .HasColumnType("int");

                    b.Property<string>("FotoPerfil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoUsuarioId")
                        .HasColumnType("int");

                    b.Property<bool>("esAcompanante")
                        .HasColumnType("bit");

                    b.Property<bool>("esPaciente")
                        .HasColumnType("bit");

                    b.Property<bool>("esTutor")
                        .HasColumnType("bit");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Usuario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("TEAyudo_JT.Tutor", b =>
                {
                    b.HasBaseType("TEAyudo_JT.Usuario");

                    b.Property<string>("CertUniDisc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ChatConversacionId")
                        .HasColumnType("int");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.HasIndex("ChatConversacionId");

                    b.HasDiscriminator().HasValue("Tutor");
                });

            modelBuilder.Entity("AcompananteObraSocial", b =>
                {
                    b.HasOne("TEAyudo_JT.Acompanante", null)
                        .WithMany()
                        .HasForeignKey("AcompanantesAcompananteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TEAyudo_JT.ObraSocial", null)
                        .WithMany()
                        .HasForeignKey("ObrasSocialesObraSocialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ChatConversacion", b =>
                {
                    b.HasOne("TEAyudo_JT.Acompanante", "Acompanante")
                        .WithMany("ChatConversaciones")
                        .HasForeignKey("ChatConversacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TEAyudo_JT.Tutor", "Tutor")
                        .WithMany("ChatConversaciones")
                        .HasForeignKey("ChatConversacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acompanante");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("EstadoPostulacionPostulacion", b =>
                {
                    b.HasOne("TEAyudo_JT.EstadoPostulacion", null)
                        .WithMany()
                        .HasForeignKey("EstadosDePostulacionEstadoPostulacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TEAyudo_JT.Postulacion", null)
                        .WithMany()
                        .HasForeignKey("PostulacionesPostulacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TEAyudo_JT.Acompanante", b =>
                {
                    b.HasOne("ChatConversacion", null)
                        .WithMany("Acompanantes")
                        .HasForeignKey("ChatConversacionId");
                });

            modelBuilder.Entity("TEAyudo_JT.ChatMensaje", b =>
                {
                    b.HasOne("ChatConversacion", "ChatConversacion")
                        .WithMany("ChatMensajes")
                        .HasForeignKey("ChatConversacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TEAyudo_JT.Usuario", "Usuario")
                        .WithMany("ChatMensajes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatConversacion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TEAyudo_JT.DisponibilidadHoraria", b =>
                {
                    b.HasOne("TEAyudo_JT.Postulacion", null)
                        .WithMany("DisponibilidadesHoraria")
                        .HasForeignKey("PostulacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TEAyudo_JT.Especialidad", b =>
                {
                    b.HasOne("TEAyudo_JT.Acompanante", null)
                        .WithMany("Especialidades")
                        .HasForeignKey("AcompananteId");
                });

            modelBuilder.Entity("TEAyudo_JT.EstadoUsuario", b =>
                {
                    b.HasOne("TEAyudo_JT.Acompanante", null)
                        .WithMany("EstadosDeUsuario")
                        .HasForeignKey("AcompananteId");

                    b.HasOne("TEAyudo_JT.Usuario", null)
                        .WithMany("EstadosDeUsuario")
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("TEAyudo_JT.Paciente", b =>
                {
                    b.HasOne("TEAyudo_JT.Tutor", null)
                        .WithMany("Pacientes")
                        .HasForeignKey("TutorUsuarioId");
                });

            modelBuilder.Entity("TEAyudo_JT.Postulacion", b =>
                {
                    b.HasOne("TEAyudo_JT.Acompanante", null)
                        .WithMany("Postulaciones")
                        .HasForeignKey("AcompananteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TEAyudo_JT.Tutor", b =>
                {
                    b.HasOne("ChatConversacion", null)
                        .WithMany("Tutores")
                        .HasForeignKey("ChatConversacionId");
                });

            modelBuilder.Entity("ChatConversacion", b =>
                {
                    b.Navigation("Acompanantes");

                    b.Navigation("ChatMensajes");

                    b.Navigation("Tutores");
                });

            modelBuilder.Entity("TEAyudo_JT.Acompanante", b =>
                {
                    b.Navigation("ChatConversaciones");

                    b.Navigation("Especialidades");

                    b.Navigation("EstadosDeUsuario");

                    b.Navigation("Postulaciones");
                });

            modelBuilder.Entity("TEAyudo_JT.Postulacion", b =>
                {
                    b.Navigation("DisponibilidadesHoraria");
                });

            modelBuilder.Entity("TEAyudo_JT.Usuario", b =>
                {
                    b.Navigation("ChatMensajes");

                    b.Navigation("EstadosDeUsuario");
                });

            modelBuilder.Entity("TEAyudo_JT.Tutor", b =>
                {
                    b.Navigation("ChatConversaciones");

                    b.Navigation("Pacientes");
                });
#pragma warning restore 612, 618
        }
    }
}
